name: Update Games Calendar

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: disable quotePath
        run: git config --global core.quotePath false

      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: List files
        run: ls -R

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Update Data
        env:
          CI_ENV: ci
        run: node ./generate.js

      - name: commit changed files
        run: git remote set-url origin ${{ secrets.ssh }} && git add . && git commit -m "Updating events at $(date)" && git fetch origin master && git push origin master
