name: Update Games Calendar

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"


concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: disable quotePath
        run: git config --global core.quotePath false

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: List files
        run: ls -R

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update wishlist.txt
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"

          git fetch origin master
          git checkout master -- update_wishlist_list.js

          git fetch origin release
          git checkout release

          curl 'https://www.steamwishlistcalculator.com/api/wishlist?steamId=76561198171618942&countryCode=US' > wishlist.json
          node ./update_wishlist_list.js > wishlist.txt

          git add wishlist.txt

      - name: commit
        if: ${{ github.event_name != 'schedule' }}
        run: |
          if ! git diff --exit-code --cached; then
            git commit -am "Wishlist: ${{ github.event.head_commit.message }} at $(date -u "+%Y-%m-%dT %H:%M:%S%Z")"
            git push origin release
          fi

      - name: commit
        if: ${{ github.event_name == 'schedule' }}
        run: |
          if ! git diff --exit-code --cached; then
            git commit -am "Update wishlist at $(date -u "+%Y-%m-%dT %H:%M:%S%Z")"
            git push origin release
          fi
