name: Update Games Calendar

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */4 * * *"


concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: disable quotePath
        run: git config --global core.quotePath false

      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: List files
        run: ls -R

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Update Data
        env:
          CI_ENV: ci
        run: |
          set -x
          git fetch origin release
          git checkout origin/release -- *.json
          node ./generate.js list.txt
          git status

      - name: add changed files
        run: |
          set -x
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git status
          git fetch origin master
          git stash -- *.json
          git checkout release
          git status
          git stash show
          git checkout stash@{0} *.json 
          
          # idk why but git 2.43 will raise an error says `fatal: '--merge', '--ours', or '--theirs' cannot be used when checking out of a tree` 
          # git checkout stash@{0} --theirs *.json
          git checkout master -- static.json override.json index.html float.css favicon.svg .gitignore
          git status

      - name: commit
        if: ${{ github.event_name != 'schedule' }}
        run: |
          if ! git diff --exit-code --cached; then
            git commit -am "${{ github.event.head_commit.message }} at $(date -u "+%Y-%m-%dT %H:%M:%S%Z")"
            git push origin release
          fi

      - name: commit
        if: ${{ github.event_name == 'schedule' }}
        run: |
          if ! git diff --exit-code --cached; then
            git commit -am "Daily update at $(date -u "+%Y-%m-%dT %H:%M:%S%Z")"
            git push origin release
          fi
