name: Update Games Calendar

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: disable quotePath
        run: git config --global core.quotePath false

      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: List files
        run: ls -R

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Update Data
        env:
          CI_ENV: ci
        run: |
          set -x
          git fetch origin release
          git checkout origin/release -- events.json
          node ./generate.js

      - name: commit changed files
        run: |
          set -x
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git fetch origin master
          git stash -- events.json
          git checkout release
          git checkout stash@{0} --theirs .
          git checkout master -- static.json override.json index.html float.css
          git status
          if ! git diff --exit-code --cached; then
            git commit -am "Updating events at $(date)"
            git push origin release
          fi
